library(MASS)
library(rpart)
head(birthwt)
hist(birthwt$bwt)
table(birthwt$low)
str(birthwt)
cols<-c('low','smoke','ht','ui')
birthwt[cols]<-lapply(birthwt[cols],as.factor)
str(birthwt)
set.seed(1)
trainset<-sample(1:nrow(birthwt),0.75*nrow(birthwt))
dim(trainset)
birthtree<-rpart(low~.-bwt,data = birthwt[trainset,],method = 'class')
plot(birthtree)
text(birthtree,pretty=0)
summary(birthtree)
birthPred<-predict(birthtree,birthwt[-trainset,],type='class')
dt_tab<-table(birthPred,birthwt[-trainset,]$low)
dt_tab
acc_val<-sum(diag(dt_tab))/sum(dt_tab)
print(paste('Accuracy for the test',acc_val*100))
